# Generated by Django 4.2.2 on 2023-07-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='default_chatroom.jpg', upload_to='chatroom_pics'),
        ),
    ]
